CREATE STORAGE INTEGRATION SNOWFLAKE_HANDS_ON
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<ROLE ARN>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<BUCKET>/<PATH>/');
  
  
DESC INTEGRATION SNOWFLAKE_HANDS_ON;
  
  
GRANT CREATE STAGE ON SCHEMA DB.SCHEMA TO ROLE USER_ROLE;

GRANT USAGE ON INTEGRATION SNOWFLAKE_HANDS_ON TO ROLE USER_ROLE;


USE SCHEMA DB.SCHEMA;

CREATE STAGE my_s3_stage
  STORAGE_INTEGRATION = SNOWFLAKE_HANDS_ON
  URL = 's3://<BUCKET>/<PATH>/'
  FILE_FORMAT = <FILE_FORMAT>;
  
LIST @my_s3_stage;