profile = "miad"
project = "snowflake-hands-on"
region  = "us-east-1"
bucket_name = "okr4-ho1-c2g3"
group_name = "c2g3"
snowflake_access_policy = "snowflake_access_policy"
snowflake_role = "snowflake_role"